<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="abokhlaifa" ignored="0" name="EmployeeRestAssuredTests" tests="11" failures="1" timestamp="28 Aug 2019 16:42:18 GMT" time="11.239" errors="0">
  <testcase name="checkResponseBody" time="0.817" classname="com.almatar.FBOapi.tests.TC00_GetAllEmployees"/>
  <testcase name="addEmployeeRecord" time="1.165" classname="com.almatar.FBOapi.tests.TC01_addEmployee"/>
  <testcase name="addEmployeeRecord" time="0.5" classname="com.almatar.FBOapi.tests.TC01_addEmployee"/>
  <testcase name="addEmployeeRecord" time="0.511" classname="com.almatar.FBOapi.tests.TC01_addEmployee"/>
  <testcase name="addEmployeeRecord" time="0.478" classname="com.almatar.FBOapi.tests.TC01_addEmployee"/>
  <testcase name="addEmployeeRecord" time="0.541" classname="com.almatar.FBOapi.tests.TC01_addEmployee"/>
  <testcase name="addEmployeeRecord" time="0.508" classname="com.almatar.FBOapi.tests.TC01_addEmployee"/>
  <testcase name="addEmployeeRecord" time="0.519" classname="com.almatar.FBOapi.tests.TC01_addEmployee"/>
  <testcase name="addEmployeeRecord" time="0.469" classname="com.almatar.FBOapi.tests.TC01_addEmployee"/>
  <testcase name="addEmployeeRecord" time="0.541" classname="com.almatar.FBOapi.tests.TC01_addEmployee"/>
  <testcase name="authenticate" time="0.003" classname="com.almatar.FBOapi.tests.TC02_authentication">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.almatar.FBOapi.tests.TC02_authentication.authenticate(TC02_authentication.java:49)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- authenticate -->
</testsuite> <!-- EmployeeRestAssuredTests -->
